[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/",
    "@uniswap/v3-periphery/contracts=lib/v3-periphery/contracts/",
    "@uniswap/v3-core/contracts=lib/v3-core/contracts/",
    "@forge-std=lib/forge-std/",
]   

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
